name: diamond
description: A compositor using the waybright library
version: 1.0.0
repository: https://github.com/brighta19/diamond

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  waybright:
    git:
      url: https://github.com/brighta19/waybright.git
      ref: 6de06502b03c4bbd388142c18971f28bc8c93c7c
    # path: '../waybright'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

publish_to: none
