name: diamond
description: A compositor using the waybright library
version: 1.0.0
repository: https://github.com/brighta19/diamond

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  waybright:
    git:
      url: https://github.com/brighta19/waybright.git
      ref: b1ed744bf5543ac0e7dc9534f6303909b3bf4b30
    # path: '../waybright'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

publish_to: none
